#!/usr/bin/php
<?php
ini_set( 'default_socket_timeout', 600 );

$directory = 'themes';
$download = 'zips/%s.zip';
$url = 'http://wordpress.org/themes/download/%s.latest-stable.zip?nostats=1';

echo "Determining most recent SVN revision...\r\n";
try {
	$changelog = @file_get_contents( 'http://themes.trac.wordpress.org/log/?format=changelog&stop_rev=HEAD' );
	if ( !$changelog )
		throw new Exception( 'Could not fetch the SVN changelog' );
	preg_match( '#\[([0-9]+)\]#', $changelog, $matches );
	if ( !$matches[1] )
		throw new Exception( 'Could not determine most recent revision.' );
} catch ( Exception $e ) {
	die( $e->getMessage() . "\r\n" );
}
$svn_last_revision = (int) $matches[1];
echo "Most recent SVN revision: " . $svn_last_revision . "\r\n";
if ( file_exists( $directory . '/.last-revision' ) ) {
	$last_revision = (int) file_get_contents( $directory . '/.last-revision' );
	echo "Last synced revision: " . $last_revision . "\r\n";
} else {
	$last_revision = false;
	echo "You have not yet performed a successful sync. Settle in. This will take a while.\r\n";
}

$start_time = time();

if ( $last_revision != $svn_last_revision ) {
	if ( $last_revision ) {
		$changelog_url = sprintf( 'http://themes.trac.wordpress.org/log/?verbose=on&mode=follow_copy&format=changelog&rev=%d&limit=%d', $svn_last_revision, $svn_last_revision - $last_revision );
		$changes = file_get_contents( $changelog_url );

		if ( empty( $changes ) )
			die( 'Could not fetch themes' );

		preg_match_all( '#^' . "\t" . '*\* ([^/A-Z ]+)[ /].* \((added|modified|deleted|moved|copied)\)' . "\n" . '#m', $changes, $matches );
		$themes = array_unique( $matches[1] );
	} else {
		$themes = file_get_contents( 'http://themes.svn.wordpress.org/' );

		if ( empty( $themes ) )
			die( 'Could not fetch themes' );

		preg_match_all( '#<li><a href="([^/]+)/">([^/]+)/</a></li>#', $themes, $matches );
		$themes = $matches[1];
	}

	$i = 0;
	foreach ( $themes as $theme ) {
		$theme = urldecode( $theme );
		printf( "Updating (%d/%d) %s", ++$i, count( $themes ), $theme );

		$output = null; $return = null;
		exec( 'wget -q -np -O ' . escapeshellarg( sprintf($download, $theme) ) . ' ' . escapeshellarg( sprintf($url, $theme) ) . ' > /dev/null', $output, $return );

		if ( $return === 0 && file_exists( sprintf($download, $theme) ) ) {

			if ( file_exists( 'themes/' . $theme ) )
				exec( 'rm -rf ' . escapeshellarg( 'themes/' . $theme ) );

			exec( 'unzip -o -d themes ' . escapeshellarg( 'zips/' . $theme . '.zip' ) );
			exec( 'rm -rf ' . escapeshellarg( 'zips/' . $theme . '.zip' ) );
			
			echo '... successfully updated.';
		} else {
			echo '... no stable version.';
		}
		echo "\r\n";
	}

	if ( file_put_contents( $directory . '/.last-revision', $svn_last_revision ) )
		echo "[CLEANUP] Updated $directory/.last-revision to " . $svn_last_revision . "\r\n";
	else
		echo "[ERROR] Could not update $directory/.last-revision to " . $svn_last_revision . "\r\n";
}

$end_time = time();
$minutes = ( $end_time - $start_time ) / 60;
$seconds = ( $end_time - $start_time ) % 60;

echo "[SUCCESS] Done updating themes!\r\n";
echo "It took " . number_format($minutes) . " minute" . ( $minutes == 1 ? '' : 's' ) . " and " . $seconds . " second" . ( $seconds == 1 ? '' : 's' ) . " to update ". count($themes)  ." theme" . ( count($themes) == 1 ? '' : 's') . "\r\n";
echo "[DONE]\r\n";
